### ISSUE TITLE
on Sandstorm: After creating a second contact, it doesn't seem to show up

### ISSUE THREAD

**Issue by paulproteus** [phildini/logtacts#55] opened 2016-02-25 20:02 UTC
https://oasis.sandstorm.io/grain/MQi92qCDxvayXrtkoQtRov vs. https://oasis.sandstorm.io/grain/MQi92qCDxvayXrtkoQtRov/2/

I can work on providing steps to reproduce, and/or a patch.

**Comment by phildini** [comment] 2016-02-25 20:07
STR would be great, because right now I can't repro.

**Comment by phildini** [comment] 2016-03-12 17:33
Closing as "Cannot reproduce" for the moment; feel free to re-open if the issue still occurs.

**Closed by phildini** 2016-03-12 17:33 UTC
Labels: sandstorm
