### ISSUE TITLE
Sandstorm - Update Didn't Save

### ISSUE THREAD

**Issue by ocdtrekkie** [phildini/logtacts#62] opened 2016-03-13 07:40 UTC
#### What you expected to happen

After upgrading a Contact Otter grain to 0.0.4, I tried adding some additional email fields, a Twitter, and a phone number to a pre-existing contact (from before the update). I clicked Save, and expected it to save.

#### What actually happened

After clicking Save, I was returned to the edit contact screen, without any of my changes.

#### Steps to reproduce
- Explained above

##### Is this on sandstorm?
Yes

**Comment by phildini** [comment] 2016-03-14 05:55
@ocdtrekkie could you provide any more detail? is there anything suspicious in the log? I'm not able to reproduce your issue.

**Comment by ocdtrekkie** [comment] 2016-03-14 05:58
Not that I can see, @phildini 

All that's generated as I try to use the app is this:

[pid: 246|app: 0|req: 1/1] 127.0.0.1 () {54 vars in 1088 bytes} [Mon Mar 14 05:56:07 2016] GET / => generated 8212 bytes in 346 msecs (HTTP/1.1 200) 5 headers in 355 bytes (1 switches on core 0)
[pid: 242|app: 0|req: 1/2] 127.0.0.1 () {54 vars in 1188 bytes} [Mon Mar 14 05:56:22 2016] GET /1/ => generated 8637 bytes in 250 msecs (HTTP/1.1 200) 4 headers in 224 bytes (1 switches on core 0)
[pid: 242|app: 0|req: 2/3] 127.0.0.1 () {54 vars in 1198 bytes} [Mon Mar 14 05:56:24 2016] GET /edit/1/ => generated 16600 bytes in 54 msecs (HTTP/1.1 200) 4 headers in 224 bytes (1 switches on core 0)
[pid: 242|app: 0|req: 3/4] 127.0.0.1 () {58 vars in 1315 bytes} [Mon Mar 14 05:56:30 2016] POST /edit/1/ => generated 16600 bytes in 55 msecs (HTTP/1.1 200) 4 headers in 224 bytes (1 switches on core 0)
[pid: 242|app: 0|req: 4/5] 127.0.0.1 () {54 vars in 1198 bytes} [Mon Mar 14 05:57:14 2016] GET /edit/1/ => generated 16600 bytes in 89 msecs (HTTP/1.1 200) 4 headers in 224 bytes (1 switches on core 0)
[pid: 242|app: 0|req: 5/6] 127.0.0.1 () {58 vars in 1315 bytes} [Mon Mar 14 05:57:27 2016] POST /edit/1/ => generated 16600 bytes in 52 msecs (HTTP/1.1 200) 4 headers in 224 bytes (1 switches on core 0)
[pid: 242|app: 0|req: 6/7] 127.0.0.1 () {58 vars in 1315 bytes} [Mon Mar 14 05:57:33 2016] POST /edit/1/ => generated 16600 bytes in 51 msecs (HTTP/1.1 200) 4 headers in 224 bytes (1 switches on core 0)

The grain contains no sensitive data, I could send you a backup?

**Comment by phildini** [comment] 2016-03-31 09:45
I've looked at @ocdtrekkie's backup and can't reproduce the issue he's talking about. I'm going to close this for now, but am totally willing to reopen it if the issue becomes clearer.

**Closed by phildini** 2016-03-31 09:45 UTC

**Comment by ocdtrekkie** [comment] 2016-03-31 14:02
That's unfortunate, because I am completely unable to use this app.

I'm testing in a different environment right now as well, IE11 and Edge, the Save button doesn't even let me click it, it seems.
